In [3]:
import numpy as np
from scipy.sparse import csr_matrix
import pandas as pd

In [4]:
#Matrice di incidenza per la descrizione della topologia dell'impianto elettrico
L1=np.matrix([[-1,0,0,0,0,0,0,0,0,0,0,0,0,0]\
            ,[1,-1,0,0,0,0,0,0,0,0,0,0,0,0]\
            ,[1,0,-1,0,0,0,0,0,0,0,0,0,0,0]\
            ,[1,0,0,-1,0,0,0,0,0,0,0,0,0,0]\
            ,[1,0,0,0,-1,0,0,0,0,0,0,0,0,0]\
            ,[1,0,0,0,0,-1,0,0,0,0,0,0,0,0]\
            ,[1,0,0,0,0,0,-1,0,0,0,0,0,0,0]\
            ,[1,0,0,0,0,0,0,-1,0,0,0,0,0,0]\
            ,[0,0,0,0,0,0,0,1,-1,0,0,0,0,0]\
            ,[0,0,0,0,0,0,0,1,0,-1,0,0,0,0]\
            ,[0,0,0,0,0,0,0,1,0,0,-1,0,0,0]\
            ,[0,0,0,0,0,0,0,1,0,0,0,-1,0,0]\
            ,[0,0,0,0,0,0,0,1,0,0,0,0,-1,0]\
            ,[0,0,0,0,0,0,0,1,0,0,0,0,0,-1]])

Linv=np.linalg.inv(L1)

print(Linv)
len(Linv)

[[-1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -1. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -1. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -1. -0. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -0. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -1. -0. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -0. -1. -0. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -0. -0. -1. -0. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -0. -0. -0. -1. -0. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -0. -0. -0. -0. -1. -0.]
 [-1. -0. -0. -0. -0. -0. -0. -1. -0. -0. -0. -0. -0. -1.]]


14

In [20]:
#Matrice delle impedenze
#contentente le impedenze di tuttii rami costituenti la rete, e disposti lunga la diagonale
Z1=(2.62+9.815j)*10**-3  #impedenza del trasformatore scelto, in Ohm, che descrive il primo ramo della rete
Z2=(10.287+1.634j)*10**-3 #impedenza della linea che collega il nodo 2
Z3=(23.143+3.676j)*10**-3  
Z4=(126+5.718j)*10**-3
Z5=(63+2.859j)*10**-3
Z6=(108+4.901j)*10**-3
Z7=(153+6.943j)*10**-3
Z8=(7.5+4.084j)*10**-3
Z9=(60+1.634j)*10**-3
Z10=(135+3.676j)*10**-3
Z11=(210+5.718j)*10**-3
Z12=(60+1.634j)*10**-3
Z13=(135+3.676j)*10**-3
Z14=(210+5.718j)*10**-3

Z=np.diag([Z1,Z2,Z3,Z4,Z5,Z6,Z7,Z8,Z9,Z10,Z11,Z12,Z13,Z14])
# # Vettore delle potenze assorbite
P1= (20+0j)*10**3 #power_consumption-power_pv #al nodo 1, che corrisponde al QGBT, sono direttamente collegati il carico dell'edificio e la produzione da pv, per cui risulta il netto dei due
P2 = (50+0j)*10**3
P3= (50+0j)*10**3
P4= (22+0j)*10**3
P5= (22+0j)*10**3
P6= (22+0j)*10**3
P7= (22+0j)*10**3
P8= (22+0j)*10**3
P9= (22+0j)*10**3
P10= (22+0j)*10**3
P11= (22+0j)*10**3
P12= (22+0j)*10**3
P13= (22+0j)*10**3
P14= (22+0j)*10**3
S=np.array([P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14]).reshape(len(Linv),1)  
#la funzione reshape serve a rendere un vettore colonna

# Vettore delle tenzioni nodali di inizializzazione
Vini=(np.array([1]*len(Linv))).reshape(len(Linv),1)
# # Errore accettabile
epsilon=10**-6

print(S)


[[20000.+0.j]
 [50000.+0.j]
 [50000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]
 [22000.+0.j]]


In [22]:
def ZIPcurrent(coeff=0,voltage=1,impedance=1,apparent_power=1):
    # if coeff==0:#potenza assegnata
    current=apparent_power.conjugate()/voltage.conjugate()
    # elif coeff==1:#corrente assegnata
   
    # elif coeff==2:#impedenza assegnata

    return current

def backward(voltage,apparent_power=S):
    #calcolo correndi nodali
    current_node=ZIPcurrent(voltage=voltage,apparent_power=apparent_power,impedance=Z)
    #ricavo le correnti di linea
    curr_line=Linv.T*current_node
    # print(curr_line)
    return curr_line

def foreward(curr_line):
    #calcolo tensioni nodali
    V=Vini-Linv*Z*curr_line
    # print(V)
    return V

def error(voltage,voltage_old):
    error=abs(voltage-voltage_old)/abs(voltage_old)
    return max(error)


voltage=Vini
voltage_old=voltage
max_iter=1000
for k in range(max_iter):
    curr_line=backward(voltage=voltage,apparent_power=S)
    voltage_old=voltage
    voltage=foreward(curr_line=curr_line)
    # print(k,error(voltage,voltage_old))
    if error(voltage,voltage_old) <epsilon:
        print(k,error(voltage,voltage_old))
        break


results=pd.DataFrame(voltage,columns=["V"])
results['I']=curr_line
results['Node']=range(1,len(voltage)+1)
results.set_index('Node',inplace=True)
results


# dictVoltages={}
# for i in range(len(voltage)):
#     dictVoltages["V"+str(i+1)]=abs(voltage[i][0])

# dictLineCurr={}
# for i in range(len(voltage)):
#     dictLineCurr["I"+str(i+1)]=(curr_line[i][0])



V                    I
Node                                         
1     0.536286+0.117729j -0.575809+47.091688j
2     0.508005+0.201562j -1.419010+ 8.374850j
3     0.502067+0.292001j -0.275574+ 7.574007j
4     0.564859+0.466766j  0.351751+ 2.754172j
5     0.527900+0.328380j  0.018577+ 3.342826j
6     0.554120+0.431954j  0.296545+ 2.896039j
7     0.580493+0.514205j  0.405687+ 2.572936j
8     0.479036+0.244115j  1.189968+16.203566j
9     0.482717+0.399681j  0.131861+ 2.589180j
10    0.515633+0.534263j  0.329372+ 2.140273j
11    0.548189+0.636970j  0.379958+ 1.860389j
12    0.482717+0.399681j  0.131861+ 2.589180j
13    0.515633+0.534263j  0.329372+ 2.140273j
14    0.548189+0.636970j  0.379958+ 1.860389j

In [74]:
import numpy as np
import pandas as pd

#Matrice di incidenza per la descrizione della topologia dell'impianto elettrico
L=np.matrix([[-1,0,0,0,0,0,0,0,0,0,0,0,0,0]\
            ,[1,-1,0,0,0,0,0,0,0,0,0,0,0,0]\
            ,[1,0,-1,0,0,0,0,0,0,0,0,0,0,0]\
            ,[1,0,0,-1,0,0,0,0,0,0,0,0,0,0]\
            ,[1,0,0,0,-1,0,0,0,0,0,0,0,0,0]\
            ,[1,0,0,0,0,-1,0,0,0,0,0,0,0,0]\
            ,[1,0,0,0,0,0,-1,0,0,0,0,0,0,0]\
            ,[1,0,0,0,0,0,0,-1,0,0,0,0,0,0]\
            ,[0,0,0,0,0,0,0,1,-1,0,0,0,0,0]\
            ,[0,0,0,0,0,0,0,1,0,-1,0,0,0,0]\
            ,[0,0,0,0,0,0,0,1,0,0,-1,0,0,0]\
            ,[0,0,0,0,0,0,0,1,0,0,0,-1,0,0]\
            ,[0,0,0,0,0,0,0,1,0,0,0,0,-1,0]\
            ,[0,0,0,0,0,0,0,1,0,0,0,0,0,-1]])

Linv = np.linalg.inv(L)

#definizione delle grandezze base per il sistema in esame
Vbase= 400 #V
Sbase= 630 #kVA (potenza del trasformatore MT/BT)
Zbase= Vbase**2/(Sbase*10**3) #Ohm
Ibase=Sbase*10**3/Vbase #A

#Matrice delle impedenze
#contentente le impedenze di tuttii rami costituenti la rete, e disposti lunga la diagonale, calcolato in p.u.

Z1=(2.62+9.815j)*10**-3 /Zbase #impedenza del trasformatore scelto, in Ohm, che descrive il primo ramo della rete
Z2=(14.4+1.63j)*10**-3 /Zbase #impedenza della linea che collega il nodo 2 al nodo 1
Z3=(32.4+3.68j)*10**-3  /Zbase
Z4=(126+5.718j)*10**-3 /Zbase
Z5=(63+2.859j)*10**-3 /Zbase
Z6=(108+4.901j)*10**-3 /Zbase
Z7=(153+6.943j)*10**-3 /Zbase
Z8=(7.5+4.084j)*10**-3 /Zbase
Z9=(36+1.63j)*10**-3 /Zbase
Z10=(81+3.68j)*10**-3 /Zbase
Z11=(78.8+5.72j)*10**-3 /Zbase
Z12=(36+1.63j)*10**-3 /Zbase
Z13=(81+3.68j)*10**-3  /Zbase
Z14=(78.8+5.72j)*10**-3  /Zbase

Z=np.diag([Z1,Z2,Z3,Z4,Z5,Z6,Z7,Z8,Z9,Z10,Z11,Z12,Z13,Z14])

# Potenza netta direttamente connessa al nodo 1 (QGBT)
P_building = 3.59*10**5 + 1.18*10**5j # potenza assorbita dall'edificio
P_pv = 0       # potenza generata dal PV
#S1_net = (np.sqrt((3.59*10**5)**2+(1.18*10**5)**2))/(Sbase*10**3)
S1_net = ((P_building))/(Sbase*10**3)

#Potenza ai nodi da 2 a 14 (colonnine)
S2=(5*10**4 + 0j)/(Sbase*10**3)  #DC
S3=(5*10**4 + 0j)/(Sbase*10**3)  #DC
S4=(2.2*10**4 + 0j)/(Sbase*10**3) #AC
S5= (2.2*10**4 + 0j)/(Sbase*10**3)  #AC
S6= (2.2*10**4 + 0j)/(Sbase*10**3)  #AC
S7= (2.2*10**4 + 0j)/(Sbase*10**3)  #AC
S8= (0+0j)/(Sbase*10**3)  #non si sono carichi direttamente connessi al nodo 8 (QSBT)
S9= (2.2*10**4 + 0j)/(Sbase*10**3)  #AC
S10= (2.2*10**4 + 0j)/(Sbase*10**3)  #AC
S11= (2.2*10**4 + 0j) /(Sbase*10**3) #AC
S12= (2.2*10**4 + 0j) /(Sbase*10**3) #AC
S13= (2.2*10**4 + 0j) /(Sbase*10**3) #AC
S14= (2.2*10**4 + 0j) /(Sbase*10**3) #AC

# Vettore delle potenze assorbite/generate (negativo per generazione) ad ogni nodo, calcolato in p.u.

S = np.array([S1_net,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13,S14]).reshape(len(Linv), 1)

# Vettore delle tensioni nodali di inizializzazione
Vini = (np.array([1] * len(Linv))).reshape(len(Linv), 1)  #ad ogni modo si impone una tensione di inizializzazione pari a 1 p.u.

# Errore accettabile
epsilon = 10**-17

def ZIPcurrent(coeff=0, voltage=1, impedance=1, apparent_power=1): #Definizione della funzione per il calcolo delle correnti di carico:
    current = apparent_power.conjugate() / voltage.conjugate()
    return current

def backward(voltage, apparent_power=S): # Definizione della funzione backward per il calcolo delle correnti di linea
    current_node = ZIPcurrent(voltage=voltage, apparent_power=apparent_power, impedance=Z)
    curr_line = Linv.T * current_node
    return curr_line

def foreward(curr_line):  #Definizione della funzione foreward per il calcolo delle tensioni nodali:
    V = Vini - Linv * Z * curr_line
    return V

def error(voltage, voltage_old):
    error = abs(voltage - voltage_old) / abs(voltage_old)
    return max(error)

voltage = Vini
voltage_old = voltage
max_iter = 1000

for k in range(max_iter):
    curr_line = backward(voltage=voltage, apparent_power=S)
    voltage_old = voltage
    voltage = foreward(curr_line=curr_line)
    if error(voltage, voltage_old) < epsilon:
        print(k, error(voltage, voltage_old))
        break

results = pd.DataFrame(voltage, columns=["V"])
results['I'] = curr_line
results['Node'] = range(1, len(voltage) + 1)
results.set_index('Node', inplace=True)

# Calcolo del valore efficace
results['V_eff'] = np.abs(results['V']) *Vbase # Valore efficace delle tensioni
results['I_eff'] = np.abs(results['I']) *Ibase # Valore efficace delle correnti

results


13 [[0.]]


V                   I       V_eff        I_eff
Node                                                                 
1     0.986839-0.041907j -1.097090+0.047702j  395.091203  1729.548852
2     0.982243-0.042228j -0.080651+0.003467j  393.260300   127.142252
3     0.976438-0.042630j -0.081126+0.003542j  390.947140   127.894528
4     0.968957-0.041944j -0.035972+0.001557j  387.945741    56.708961
5     0.977980-0.041929j -0.035641+0.001528j  391.551405    56.186748
6     0.971552-0.041940j -0.035876+0.001549j  388.982867    56.557761
7     0.965037-0.041948j -0.036118+0.001570j  386.379359    56.938859
8     0.980319-0.045073j -0.215303+0.010014j  392.542019   339.469360
9     0.975244-0.045068j -0.035731+0.001651j  390.513911    56.336021
10    0.968824-0.045061j -0.035967+0.001673j  387.948571    56.708548
11    0.969126-0.045361j -0.035954+0.001683j  388.074704    56.690116
12    0.975244-0.045068j -0.035731+0.001651j  390.513911    56.336021
13    0.968824-0.045061j -0.035967+0.001673j  387.948571    56.708548
14    0.969126-0.045361j -0.035954+0.001683j  388.074704    56.690116

377895.48819746444

(359000.5836040441-1.0255760916425638j)